# Generated by Django 6.0 on 2026-01-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_remove_destination_created_at_destination_price_and_more'),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='destination',
        ),
        migrations.AddField(
            model_name='plan',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='destinations',
            field=models.ManyToManyField(to='destinations.destination'),
        ),
        migrations.AddField(
            model_name='plan',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plan',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
